import type { Format, TransformedToken } from 'style-dictionary/types';

type TokenLeaf = { value: string; cssVar: string };
type TokenTree = { [key: string]: TokenTree | TokenLeaf };

function buildTree(tokens: TransformedToken[], prefix: string): TokenTree {
  const root: TokenTree = {};
  for (const token of tokens) {
    const parts = token.path;
    let node = root;
    for (let i = 0; i < parts.length - 1; i++) {
      const key = parts[i];
      if (!node[key] || 'value' in (node[key] as object)) node[key] = {};
      node = node[key] as TokenTree;
    }
    const leaf = parts[parts.length - 1];
    node[leaf] = {
      value: String(token.$value ?? token.value),
      cssVar: prefix ? `--${prefix}-${parts.join('-')}` : `--${parts.join('-')}`,
    };
  }
  return root;
}

function isNumericKeys(obj: TokenTree): boolean {
  return Object.keys(obj).length > 0 && Object.keys(obj).every(k => !isNaN(Number(k)));
}

function isLeaf(val: unknown): val is TokenLeaf {
  return typeof val === 'object' && val !== null && 'value' in val && 'cssVar' in val;
}

function buildInterface(tree: TokenTree, indent = ''): string {
  const lines: string[] = [];
  for (const [key, val] of Object.entries(tree)) {
    if (isLeaf(val)) {
      lines.push(`${indent}${JSON.stringify(key)}: Token;`);
    } else if (isNumericKeys(val as TokenTree)) {
      const keys = Object.keys(val as TokenTree).join(' | ');
      lines.push(`${indent}${JSON.stringify(key)}: Record<${keys}, Token>;`);
    } else {
      lines.push(`${indent}${JSON.stringify(key)}: {`);
      lines.push(buildInterface(val as TokenTree, indent + '  '));
      lines.push(`${indent}};`);
    }
  }
  return lines.join('\n');
}

export const dtsFormat: Format = {
  name: 'custom/typescript-declarations',
  format: ({ dictionary, options }) => {
    const prefix = (options?.prefix as string) ?? '';
    const tree = buildTree(dictionary.allTokens, prefix);
    const lines: string[] = [
      '// Auto-generated by @kommo-crm/tokens. Do not edit manually.',
      '',
      'export interface Token {',
      '  /** Resolved CSS value */',
      '  value: string;',
      '  /** CSS custom property name */',
      '  cssVar: string;',
      '}',
      '',
    ];

    for (const [key, val] of Object.entries(tree)) {
      const camel = key.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
      lines.push(`export declare const ${camel}: {`);
      lines.push(buildInterface(val as TokenTree, '  '));
      lines.push('};');
      lines.push('');
    }

    lines.push('declare const _default: {');
    for (const key of Object.keys(tree)) {
      const camel = key.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
      lines.push(`  ${JSON.stringify(key)}: typeof ${camel};`);
    }
    lines.push('};');
    lines.push('export default _default;');

    return lines.join('\n');
  },
};
