import type { Format } from 'style-dictionary/types';
import { sortTokens } from './sort.js';
import { buildTree, isLeaf, type TokenTree } from './tree.js';

function buildInterface(tree: TokenTree, indent = ''): string {
  const lines: string[] = [];
  for (const [key, val] of Object.entries(tree)) {
    if (isLeaf(val)) {
      lines.push(`${indent}/** \`${val.cssVar}\` — ${val.value} */`);
      lines.push(`${indent}${JSON.stringify(key)}: {`);
      lines.push(`${indent}  /** \`${val.cssVar}\` */`);
      lines.push(`${indent}  readonly cssVar: ${JSON.stringify(val.cssVar)};`);
      lines.push(`${indent}  /** \`${val.value}\` */`);
      lines.push(`${indent}  readonly value: ${JSON.stringify(val.value)};`);
      lines.push(`${indent}};`);
    } else {
      lines.push(`${indent}${JSON.stringify(key)}: {`);
      lines.push(buildInterface(val as TokenTree, indent + '  '));
      lines.push(`${indent}};`);
    }
  }
  return lines.join('\n');
}

export const dtsFormat: Format = {
  name: 'custom/typescript-declarations',
  format: ({ dictionary, options }) => {
    const prefix = (options?.prefix as string) ?? '';
    const tree = buildTree(sortTokens(dictionary.allTokens), prefix);
    const lines: string[] = [
      '// Auto-generated by @kommo-crm/tokens. Do not edit manually.',
      '',
      'export interface Token {',
      '  /** Resolved CSS value */',
      '  value: string;',
      '  /** CSS custom property name */',
      '  cssVar: string;',
      '}',
      '',
    ];

    for (const [key, val] of Object.entries(tree)) {
      const camel = key.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
      lines.push(`export declare const ${camel}: {`);
      lines.push(buildInterface(val as TokenTree, '  '));
      lines.push('};');
      lines.push('');
    }

    lines.push('declare const _default: {');
    for (const key of Object.keys(tree)) {
      const camel = key.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
      lines.push(`  ${JSON.stringify(key)}: typeof ${camel};`);
    }
    lines.push('};');
    lines.push('export default _default;');

    return lines.join('\n');
  },
};
