import type { Format } from 'style-dictionary/types';

import { buildTree, isLeaf, type TokenTree } from '../utils/tree';

function buildInterface(tree: TokenTree, indent = ''): string {
  const lines: string[] = [];

  for (const [key, val] of Object.entries(tree)) {
    if (isLeaf(val)) {
      lines.push(`${indent}/** \`${val.cssVar}\` — ${val.value} */`);
      lines.push(`${indent}${JSON.stringify(key)}: {`);
      lines.push(`${indent}  /** \`${val.cssVar}\` */`);
      lines.push(`${indent}  readonly cssVar: ${JSON.stringify(val.cssVar)};`);
      lines.push(`${indent}  /** \`${val.value}\` */`);
      lines.push(`${indent}  readonly value: ${JSON.stringify(val.value)};`);
      lines.push(`${indent}};`);
    } else {
      lines.push(`${indent}${JSON.stringify(key)}: {`);
      lines.push(buildInterface(val as TokenTree, indent + '  '));
      lines.push(`${indent}};`);
    }
  }

  return lines.join('\n');
}

export const dtsFormat: Format = {
  name: 'custom/typescript-declarations',
  format: ({ dictionary, options }) => {
    const prefix = (options?.prefix as string) ?? '';
    const tree = buildTree(dictionary.allTokens, prefix);

    const shadeKeys = [
      ...new Set(
        dictionary.allTokens
          .filter((t) => t.path.length === 4)
          .map((t) => t.path[3])
      ),
    ].sort((a, b) => Number(a) - Number(b));

    const colorShadeUnion = shadeKeys.length
      ? shadeKeys.map((k) => JSON.stringify(k)).join(' | ')
      : 'never';

    const lines: string[] = [
      '// Auto-generated by @kommo-crm/crm-tokens. Do not edit manually.',
      '',
      'export interface Token {',
      '  /** Resolved CSS value */',
      '  value: string;',
      '  /** CSS custom property name */',
      '  cssVar: string;',
      '}',
      '',
      `/** Shade step keys: ${shadeKeys.join(', ')} */`,
      `export type ColorShade = ${colorShadeUnion};`,
      '',
      '/** shade step → Token */',
      'export type ColorShades = Record<ColorShade, Token>;',
      '',
      '/** color group name → ColorShades */',
      'export type Palette = Record<string, ColorShades>;',
      '',
    ];

    for (const [key, val] of Object.entries(tree)) {
      const camel = key.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
      const TypeName = camel.charAt(0).toUpperCase() + camel.slice(1);

      lines.push(`export declare const ${camel}: {`);
      lines.push(buildInterface(val as TokenTree, '  '));
      lines.push('};');
      lines.push(`export type ${TypeName} = typeof ${camel};`);
      lines.push('');
    }

    lines.push('declare const _default: {');

    for (const key of Object.keys(tree)) {
      const camel = key.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());

      lines.push(`  ${JSON.stringify(key)}: typeof ${camel};`);
    }

    lines.push('};');
    lines.push('export default _default;');

    return lines.join('\n');
  },
};
