import type { Format, TransformedToken } from 'style-dictionary/types';
import { sortTokens } from './sort.js';
import { buildTree, isLeaf, type TokenLeaf, type TokenTree } from './tree.js';

function serializeTree(tokenMap: Map<string, TransformedToken>, tree: TokenTree, path: string[] = []): string[] {
  const lines: string[] = [];
  for (const [key, val] of Object.entries(tree)) {
    const currentPath = [...path, key];
    if (isLeaf(val)) {
      const leaf = val as TokenLeaf;
      const token = tokenMap.get(currentPath.join('.'));
      lines.push(
        `/** @cssVar ${leaf.cssVar} @value ${leaf.value}${token?.comment ? ` — ${token.comment}` : ''} */`,
        `${JSON.stringify(key)}: { value: ${JSON.stringify(leaf.value)}, cssVar: ${JSON.stringify(leaf.cssVar)} },`,
      );
    } else {
      const nested = serializeTree(tokenMap, val as TokenTree, currentPath);
      lines.push(`${JSON.stringify(key)}: {`, ...nested.map(l => `  ${l}`), `},`);
    }
  }
  return lines;
}

export const jsNestedFormat: Format = {
  name: 'custom/js-nested',
  format: ({ dictionary, options }) => {
    const prefix = (options?.prefix as string) ?? '';
    const sorted = sortTokens(dictionary.allTokens);
    const tree = buildTree(sorted, prefix);
    const tokenMap = new Map(sorted.map((t) => [t.path.join('.'), t]));
    const lines = serializeTree(tokenMap, tree);
    const exports = Object.keys(tree).map(key => {
      const camel = key.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
      return `export const ${camel} = tree[${JSON.stringify(key)}];`;
    });

    return [
      '// Auto-generated by @kommo-crm/tokens. Do not edit manually.',
      '',
      'const tree = {',
      ...lines.map(l => `  ${l}`),
      '};',
      '',
      ...exports,
      '',
      'export default tree;',
    ].join('\n');
  },
};
