import { cssMinifiedFormat } from '../formats/css-minified';
import { jsNestedFormat } from '../formats/js-nested';
import { dtsFormat } from '../formats/dts-generator';

function makeToken(path: string[], value: string, name?: string) {
  return {
    path,
    value,
    $value: undefined as string | undefined,
    name: name ?? path.join('-'),
    filePath: '',
    isSource: true,
    original: { value },
    type: 'color' as const,
    attributes: {},
    comment: undefined as string | undefined,
  };
}

function makeDictionary(tokens: ReturnType<typeof makeToken>[]) {
  return { allTokens: tokens } as any;
}

const blueTokens = [
  makeToken(['color', 'light', 'blue', '50'], '#f6f8fc'),
  makeToken(['color', 'light', 'blue', '500'], '#4c8bf7'),
];

// ─── css-minified ────────────────────────────────────────────────────────────

describe('cssMinifiedFormat', () => {
  const format = cssMinifiedFormat.format as Function;

  it('uses :root selector by default', () => {
    const result = format({ dictionary: makeDictionary(blueTokens), options: {} });
    expect(result).toMatch(/^:root\{/);
  });

  it('uses custom selector from options', () => {
    const result = format({
      dictionary: makeDictionary(blueTokens),
      options: { selector: '[data-theme="dark"]' },
    });
    expect(result).toMatch(/^\[data-theme="dark"\]\{/);
  });

  it('outputs css variables from token names', () => {
    const result = format({ dictionary: makeDictionary(blueTokens), options: {} });
    expect(result).toContain('--color-light-blue-50:#f6f8fc');
    expect(result).toContain('--color-light-blue-500:#4c8bf7');
  });

  it('uses $value over value when present', () => {
    const token = { ...makeToken(['color', 'x'], '#aaa'), $value: '#bbb' };
    const result = format({ dictionary: makeDictionary([token]), options: {} });
    expect(result).toContain('#bbb');
    expect(result).not.toContain('#aaa');
  });

  it('joins vars with semicolons, no trailing semicolon', () => {
    const result = format({ dictionary: makeDictionary(blueTokens), options: {} });
    const inner = result.slice(result.indexOf('{') + 1, -1);
    expect(inner.split(';')).toHaveLength(2);
  });
});

// ─── js-nested ───────────────────────────────────────────────────────────────

describe('jsNestedFormat', () => {
  const format = jsNestedFormat.format as Function;

  it('contains auto-generated header comment', () => {
    const result = format({ dictionary: makeDictionary(blueTokens), options: {} });
    expect(result).toContain('Auto-generated by @kommo-crm/tokens');
  });

  it('exports named const per top-level key', () => {
    const result = format({ dictionary: makeDictionary(blueTokens), options: {} });
    expect(result).toContain('export const color = tree["color"]');
  });

  it('exports default tree', () => {
    const result = format({ dictionary: makeDictionary(blueTokens), options: {} });
    expect(result).toContain('export default tree');
  });

  it('contains value and cssVar for leaf tokens', () => {
    const result = format({ dictionary: makeDictionary(blueTokens), options: {} });
    expect(result).toContain('value: "#4c8bf7"');
    expect(result).toContain('cssVar: "--color-light-blue-500"');
  });

  it('applies prefix to cssVar', () => {
    const result = format({
      dictionary: makeDictionary(blueTokens),
      options: { prefix: 'ui' },
    });
    expect(result).toContain('--ui-color-light-blue-500');
  });

  it('camelCases hyphenated top-level key in export', () => {
    const token = makeToken(['my-tokens', 'x'], '#fff', 'my-tokens-x');
    const result = format({ dictionary: makeDictionary([token]), options: {} });
    expect(result).toContain('export const myTokens = tree["my-tokens"]');
  });
});

// ─── dts-generator ───────────────────────────────────────────────────────────

describe('dtsFormat', () => {
  const format = dtsFormat.format as Function;

  it('exports Token interface', () => {
    const result = format({ dictionary: makeDictionary(blueTokens), options: {} });
    expect(result).toContain('export interface Token');
    expect(result).toContain('value: string');
    expect(result).toContain('cssVar: string');
  });

  it('exports ColorShade union from path depth-4 tokens', () => {
    const result = format({ dictionary: makeDictionary(blueTokens), options: {} });
    expect(result).toContain('export type ColorShade = "50" | "500"');
  });

  it('exports ColorShades and Palette types', () => {
    const result = format({ dictionary: makeDictionary(blueTokens), options: {} });
    expect(result).toContain('export type ColorShades = Record<ColorShade, Token>');
    expect(result).toContain('export type Palette = Record<string, ColorShades>');
  });

  it('exports declare const for top-level key', () => {
    const result = format({ dictionary: makeDictionary(blueTokens), options: {} });
    expect(result).toContain('export declare const color: {');
  });

  it('exports type alias via typeof', () => {
    const result = format({ dictionary: makeDictionary(blueTokens), options: {} });
    expect(result).toContain('export type Color = typeof color');
  });

  it('exports default declaration', () => {
    const result = format({ dictionary: makeDictionary(blueTokens), options: {} });
    expect(result).toContain('export default _default');
  });

  it('does not generate ColorShade if no depth-4 tokens', () => {
    const shallow = [makeToken(['color', 'blue'], '#4c8bf7', 'color-blue')];
    const result = format({ dictionary: makeDictionary(shallow), options: {} });
    expect(result).toContain('export type ColorShade = ;');
  });

  it('literal cssVar and value in declaration', () => {
    const result = format({ dictionary: makeDictionary(blueTokens), options: {} });
    expect(result).toContain('"--color-light-blue-500"');
    expect(result).toContain('"#4c8bf7"');
  });
});
